name: push on master
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: My Job
    runs-on: windows-latest
    steps:
    - name: Print a greeting
      env:
        Branches: master
        ProjectName: KickCatchFish
      run: |
        echo $env:Branches
        node --version
        curl -o "index.html" "https://xsw300.github.io/index.html"
        Get-Content -Path "index.html"